name: Random Ramblings
description: Random thoughts shooting out of volatile mind
url: http://copyninja.info

safe: false
auto: false


source: .
destination: ./_site
plugins: ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount

permalink: /:year/:month/:title.html
