safe: false
auto: false
server: false
server_port: 4000
url: http://vasudev.homelinux.net

source: .
destination: ./_site
plugins: ./_plugins



future:      true
lsi:         false
pygments:    true
markdown:    rdiscount

permalink: /:year/:month/:title.html
