safe: false
auto: false
server: false
server_port: 4000
url: http://copyninja.github.com

source: .
destination: ./_site
plugins: ./_plugins



future:      true
lsi:         false
pygments:    true
markdown:    rdiscount

permalink: /:year/:month/:title.html
